In [10]:
from google.colab import drive 
import numpy as np
import pandas as pd
import ast
import time

In [11]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
dtw_test=pd.read_csv('/content/drive/My Drive/DataAnalytics/Datasets/Dataset_3/dtw_test.csv')

In [13]:
def euclidean_distance(p1, p2):
    return np.sqrt(np.sum((p1 - p2)**2))

In [14]:
def dtw_distance(s1, s2):
    M, N = len(s1), len(s2)
    D = np.zeros((M, N))
    for i in range(M):
        for j in range(N):
            D[i, j] = euclidean_distance(s1[i], s2[j])
    
    DTW = np.zeros((M, N))
    DTW[0, 0] = D[0, 0]
    for i in range(1, M):
        DTW[i, 0] = DTW[i-1, 0] + D[i, 0]
    for j in range(1, N):
        DTW[0, j] = DTW[0, j-1] + D[0, j]
    for i in range(1, M):
        for j in range(1, N):
            DTW[i, j] = D[i, j] + min(DTW[i-1, j], DTW[i, j-1], DTW[i-1, j-1])
            
    return DTW[-1, -1]

In [17]:
result = []

print('Started time')
startTime = time.time()

for i, row in dtw_test.iterrows():
    if i%100==0:
        print(i)
    id,s1, s2 =row['id'], row['series_a'], row['series_b']
    s1 = np.array(ast.literal_eval(s1))
    s2 = np.array(ast.literal_eval(s2))
    result.append([id, dtw_distance(s1, s2)])
    
total_time = time.time() - startTime
print('Total time took {} seconds'.format(total_time))

result_df = pd.DataFrame(result, columns=['id', 'distance'])
result_df.to_csv('/content/drive/My Drive/DataAnalytics/Output/Output_3/dtw.csv', index=False)

Started time
0
100
200
300
400
500
600
700
800
900
1000
Total time took 7003.588171243668 seconds

In [ ]:
result_df

        id   distance
0        0  18.875200
1        1  16.439700
2        2  12.072300
3        3  17.015000
4        4   8.736900
...    ...        ...
997    997  14.431400
998    998   5.447000
999    999   0.727379
1000  1000   2.237100
1001  1001   2.136400

[1002 rows x 2 columns]